# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright (C) 2026 Riversoft Studios
KERNEL_OBJ = kernel/LineKernel.o kernel/LineRenderer.o third-party/printf.o kernel/str.o kernel/version.o kernel/panic.o kernel/LineInput.o kernel/stack_chk.o kernel/LineRandom.o kernel/LineDrive.o kernel/LineFilesystem.o kernel/fat12.o kernel/LineColor.o kernel/syscall.o kernel/syscall_init.o kernel/fileno.o kernel/LineMemory.o
