# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright (C) 2026 Riversoft Studios
LDFLAGS = -T x86_64/linker.ld -ffreestanding -O2 -nostdlib
META_ARCH = x86
ARCH_OBJ = x86_64/boot.o x86_64/syscall.o
