# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright (C) 2026 Riversoft Studios
META_ARCH_OBJ = x86/bios_tools.o x86/serial.o x86/ps2_keyboard.o x86/power.o x86/prekernel.o
