# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright (C) 2026 Riversoft Studios
LDFLAGS = -T i386/linker.ld -ffreestanding -O2 -nostdlib
META_ARCH = x86
ARCH_OBJ = i386/boot.o i386/vga_console.o i386/dma.o i386/gdt.o i386/floppy.o i386/idt.o i386/timer.o i386/interrupts.o i386/syscall.o
